#%RAML 1.0 NamedExample
value: |
    {
      "customerId": 1,
      "firstName": "Amanda",
      "lastName": "Chou",
      "phoneNumber": "2037894654",
      "emailId": "achou0808@gmail.com",
      "SSN": "123-45-6789",
      "country": "TW"
    }