#%RAML 1.0
title: Quintrix Customer API
description: Executes CRUD operations on Customer Table
version: v1
protocols: 
  - HTTP
  - HTTPS
mediaType: application/json
baseUri: https://mocksvc.mulesoft.com/mocks/ea79df29-ed05-49d9-a529-32fcc511661d/api/ # baseUri: https://mocksvc.mulesoft.com/mocks/8563fdfc-4a0a-4f7a-8011-36036a7ce8c5/api/
types: 
  customer: !include customer.raml
  error: !include error.raml
  customerPost: !include customerPost.raml
  customerDelete: !include customerDelete.raml

/customers:

 post:
  description:  Create or update customers in database
  
  responses:      
   200: 
      
       body: 
        application/json:
         type: array
         items: 
          type: customer
         example: !include Examples/customers.raml

   204:
     description: Unable to create/insert the customer record
     body: 
      example: []
   400:
      body:
       application/json:
         schema: error
         example: !include Examples/error_example.raml

 get:
   description: Retreive all customer records
   queryParameters: 
     phoneNumber:
      type: string
      required: false

   responses: 
     200: 
      body: 
        application/json:
         type: array
         items: 
          type: customer
         example: !include Examples/customers.raml
     204:
      description: When no customer is found
      body: 
        example: []
     400:
      body:
       application/json:
         schema: error
         example: !include Examples/error_example.raml

 /{customerId}:
  uriParameters: 
    customerId:
     required: true
     type: integer
  delete:
   responses: 
     200:
      body:
       application/json:
        schema: customerDelete
        example: !include Examples/deleteResult.raml
     400:
      body:
       example: !include error.raml

  get:
   responses: 
    200:
     body: 
        application/json:
         type: array
         items: 
          type: customer
         example: !include Examples/customer_example.raml
    204:
     body:
      schema: nil
    400:
     description: 
     body: 
       application/json:
         schema: error
         example: !include Examples/error_example.raml