#%RAML 1.0
baseUri: https://mocksvc.mulesoft.com/mocks/e1db9ebf-2c3e-4256-88ee-8515515b081c # 
title: Quintrix Customer API
description: Executes CRUD Operations on Customer Table
version: v1
protocols: 
  - HTTPS 
  - HTTP
mediaType: application/json

types: 
  customer : !include dataTypes/customer.raml
  error: !include dataTypes/error.raml
/customers:
  post:
    description: This endpoint inserts all the records sent in the request body.
    body: 
      application/json:
        type: array
        items: 
          type : customer
        example: !include examples/customers.raml
    responses: 
      201:
        description: All Customers has been created
        body: 
          type : nil
      400:
        description: Error Message
        body: 
          application/json:
            schema: error
            example: !include examples/error.raml
  get:
    description: Retrieves all the customer records present in the database table
    queryParameters: 
      country:
        required: false
        enum: 
          - US
          - CA
          - UK
          - TW
          - CN
          - JP
          - SK
          - MX
    responses: 
      200:
        body: 
          application/json:
            type: array
            items: 
              type : customer
            example: !include examples/customers.raml
      204:
        description: No customers are available
        body: 
          application/json:
            example: []
      400:
        description: Error Message
        body: 
          application/json:
            schema: error
            example: !include examples/error.raml
  /{customerId}:
    uriParameters: 
      customerId: 
        description: Unique ID for each customer
        required: true
        type: integer
    delete:
      responses: 
        200:
          body:
            type : nil
        400:
          description: 
          body: 
            application/json:
              schema: error
              example: !include examples/error.raml
    get:
      responses: 
        200:
          body: 
            application/json:
              schema: customer
              example: !include examples/customer.raml
        204:
          body: 
            schema: nil
        400:
          description: 
          body: 
            application/json:
              schema: error
              example: !include examples/error.raml